<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__CxUBBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._.CxUBB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._.CxUBB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tutorialRepository' => ['privates', 'App\\Repository\\TutorialRepository', 'getTutorialRepositoryService', true],
        ], [
            'tutorialRepository' => 'App\\Repository\\TutorialRepository',
        ]);
    }
}
