<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZnC1jmxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZnC1jmx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZnC1jmx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'labelRepository' => ['privates', 'App\\Repository\\LabelRepository', 'getLabelRepositoryService', true],
        ], [
            'labelRepository' => 'App\\Repository\\LabelRepository',
        ]);
    }
}
