<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZLKX9fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z_LKX9f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z_LKX9f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tutorial' => ['privates', '.errored..service_locator.Z_LKX9f.App\\Entity\\Tutorial', NULL, 'Cannot autowire service ".service_locator.Z_LKX9f": it needs an instance of "App\\Entity\\Tutorial" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'tutorial' => 'App\\Entity\\Tutorial',
        ]);
    }
}
