<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X3votcvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X3votcv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X3votcv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'label' => ['privates', '.errored..service_locator.X3votcv.App\\Entity\\Label', NULL, 'Cannot autowire service ".service_locator.X3votcv": it needs an instance of "App\\Entity\\Label" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'label' => 'App\\Entity\\Label',
        ]);
    }
}
