<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rfa7TBBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rfa7TBB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rfa7TBB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tutorialInCourse' => ['privates', '.errored..service_locator.Rfa7TBB.App\\Entity\\TutorialInCourse', NULL, 'Cannot autowire service ".service_locator.Rfa7TBB": it needs an instance of "App\\Entity\\TutorialInCourse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tutorialInCourse' => 'App\\Entity\\TutorialInCourse',
        ]);
    }
}
