<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HVeVUOiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HVeVUOi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HVeVUOi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['privates', '.errored..service_locator.HVeVUOi.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.HVeVUOi": it needs an instance of "App\\Entity\\Page" but this type has been excluded in "config/services.yaml".'],
        ], [
            'page' => 'App\\Entity\\Page',
        ]);
    }
}
