<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HGxB2uSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HGxB2uS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HGxB2uS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blockRepository' => ['privates', 'App\\Repository\\BlockRepository', 'getBlockRepositoryService', true],
        ], [
            'blockRepository' => 'App\\Repository\\BlockRepository',
        ]);
    }
}
