<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D7OVwhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d7O_Vwh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d7O_Vwh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'label' => ['privates', '.errored..service_locator.d7O_Vwh.App\\Entity\\Label', NULL, 'Cannot autowire service ".service_locator.d7O_Vwh": it needs an instance of "App\\Entity\\Label" but this type has been excluded in "config/services.yaml".'],
        ], [
            'label' => 'App\\Entity\\Label',
        ]);
    }
}
