<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jj4GSY2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jj4GSY2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jj4GSY2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'page' => ['privates', '.errored..service_locator.jj4GSY2.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.jj4GSY2": it needs an instance of "App\\Entity\\Page" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'page' => 'App\\Entity\\Page',
        ]);
    }
}
