<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..ZNYPok.App\Entity\Block' shared service.
     *
     * @return \App\Entity\Block
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..ZNYPok": it needs an instance of "App\\Entity\\Block" but this type has been excluded in "config/services.yaml".');
    }
}
