<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLabelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X3votcv.App\Entity\Label' shared service.
     *
     * @return \App\Entity\Label
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.X3votcv": it needs an instance of "App\\Entity\\Label" but this type has been excluded in "config/services.yaml".');
    }
}
