<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jj4GSY2.App\Entity\Page' shared service.
     *
     * @return \App\Entity\Page
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jj4GSY2": it needs an instance of "App\\Entity\\Page" but this type has been excluded in "config/services.yaml".');
    }
}
