<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutorialTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TutorialType' shared autowired service.
     *
     * @return \App\Form\TutorialType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TutorialType.php';

        return $container->privates['App\\Form\\TutorialType'] = new \App\Form\TutorialType();
    }
}
