<?php

namespace ContainerXjiyHam;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutorial2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Z_LKX9f.App\Entity\Tutorial' shared service.
     *
     * @return \App\Entity\Tutorial
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Z_LKX9f": it needs an instance of "App\\Entity\\Tutorial" but this type has been excluded in "config/services.yaml".');
    }
}
