nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["*"] # Cambiar a ['http://frontend:4321'] o ['http://localhost:4321'] si deseas restringir
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["*"]
