<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW4G6p0c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW4G6p0c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW4G6p0c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW4G6p0c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW4G6p0c\App_KernelDevDebugContainer([
    'container.build_hash' => 'W4G6p0c',
    'container.build_id' => 'feaea137',
    'container.build_time' => 1715588184,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW4G6p0c');
