<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5xmxDJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5xmxDJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX5xmxDJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX5xmxDJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX5xmxDJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'X5xmxDJ',
    'container.build_id' => '3af88859',
    'container.build_time' => 1749541055,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5xmxDJ');
